### ISSUE TITLE
Can't view curation log entry after uploading dataset spreadsheet and its image

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1124]
**Describe the bug**

On staging deployment, Error (of type 404) message when trying to view entry for curation log for newly uploaded dataset:

Unable to resolve the request "curationlog/update/id/2587".

**To Reproduce**

After uploading a dataset spreadsheet to the system, 
then going to the dataset update form for the newly imported dataset,
then uploading an image and saving the form
I see in the curation log section an entry with action "Status changed to ImportFromEM"
If I click on view or edit button for that button, a 404 error page is loaded with message:

```
Unable to resolve the request "curationlog/update/id/2587".
```

**Expected behavior**
clicking on view or edit button for the curation log entry should show the detailed view and update form respectively

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

## Additional information

This problem also occurs on the beta website but the functionality works on the live website.

**Comment by rija** [comment]
Extract from the log when the error happens:
```
172.16.238.10 -  22/Sep/2022:08:41:29 +0000 "GET /index.php" 200

172.16.238.10 -  22/Sep/2022:08:42:02 +0000 "POST /index.php" 302

Failed to set unsafe attribute "curator_id" of "Dataset".

Failed to set unsafe attribute "manuscript_id" of "Dataset".

/tmp/phpM9EL2o

172.16.238.10 -  22/Sep/2022:08:42:08 +0000 "GET /index.php" 200

172.16.238.10 -  22/Sep/2022:08:42:14 +0000 "GET /index.php" 200

172.16.238.10 -  22/Sep/2022:08:42:22 +0000 "GET /index.php" 404

CHttpException: Unable to resolve the request "curationlog/update/id/2587". in /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php:286


Stack trace:

#0 /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('curationlog/upd...')

#1 /var/www/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()

#2 /var/www/index.php(24): CApplication->run()


}

REQUEST_URI=/curationlog/update/id/2587

HTTP_REFERER=https://gigadb-staging.pommetab.com/adminDataset/update/id/2476
```
