### ISSUE TITLE
create a script to generate the readme.txt from the database

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#154]
We need a script to generate the readme.txt for all each dataset so that they are all consistent. This function should be linked to the admin page as a button (similar to the mint DOI button), and include an "update" function that allows the readme to be re-written if changes are made to the dataset.
The format of the readme.txt is specified by example (from #55 ) in the file 
[readme_100397_combined1.txt](https://github.com/gigascience/gigadb-website/files/1642319/readme_100397_combined1.txt)
NB. The final section [Comments] should be maintained during the "update" function as this is where curators can add additional information not included in the main body.

**Comment by jessesiu** [comment]
this script will create the readme file on the Public FTP server. If the dataset is in the pending status and FTP server doesn't contain this dataset directory, it need create the dataset directory and the readme file? If we use the CNGB Public FTP server, we will not allow to create the file on the Public FTP server.

**Comment by only1chunts** [comment]
If on CNGB server, how will we create and edit readme.txt files normally? There must be a way to do it.
If no dataset directory already exists on the server then can the web-page show a message to the user to say this directory doesn't exist, please create it first and move all relevant files to it before generating the readme.txt

**Comment by only1chunts** [comment]
also, is it possible to have the button only enabled with a dataset status of Pending, Private or Published (i.e. inactive for incomplete, request or upload status datasets).

**Comment by only1chunts** [comment]
interim fix for this ticket is to have a command line script that can be run manually by curators to generate the readme.txt , its not as good as having it on the admin pages, but its better than having to generate the entire readme manually.
Jesse has made such a script to be run. It uses an API call to get the dataset information from the database, then parses it into the desired format using python. @jessesiu please append scripts here for future reference/use.

**Comment by ChrisArmit** [comment]
Problem example dataset 102272.
The file list is too long and the request is timed out. The terminal readout is below:

[chrisa@cngb-gigadb-ftp 102272]$ /usr/local/src/gigadb/readme.sh
--2022-09-13 17:21:18--  http://gigadb.org/api/readme?doi=102272&username=jesse@gigasciencejournal.com&password=19880322
Resolving gigadb.org (gigadb.org)... 218.189.16.137
Connecting to gigadb.org (gigadb.org)|218.189.16.137|:80... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
2022-09-13 17:26:22 ERROR 504: Gateway Time-out.

Traceback (most recent call last):
  File "/usr/local/src/gigadb/readxml.py", line 5, in <module>
    tree = ET.parse(sys.argv[1])
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 657, in parse
    self._root = parser.close()
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by pli888** [comment]
As part of [Sprint 16](https://github.com/orgs/gigascience/projects/40), we will implement a subset of the functionality described above which will replicate current existing functionality to create the readme file. This tool will be deployed on Bastion server to be executed as a Yii console command using `docker-compose`.

We will also include adding [external links](#1152) as part of this work.
