### ISSUE TITLE
Some GigaDB files with 0 B file size after curator upload

### ISSUE THREAD

**Issue by molcretb** [gigascience/gigadb-website#2137]
## User Story

> As a curator
>I want all dataset files added to GigaDB database to file size and checksum
>So that I can have confidence in the integrity of the file

## Acceptance Criteria

>Given I have ingested a dataset with files associated with postUpload script
>When I navigate to the dataset mockup
>Then I should see the size and the MD5 checksum information for all the files

## Additional info

**Describe the bug**
After dataset upload and postUpload scripts, some files of the dataset have size = 0 B and no MD5 checksum.

**To Reproduce**
1. Go to https://gigadb.org/dataset/view/id/102628/token/xIoEq4amYH39BT6g
2. Click on the Files tab
3. Scroll down to file 'Table_S15.csv'

EDIT: missing size and MD5 values have been manually added in dataset 102628, following same instructions as 102636

**Expected behavior**
I want all files to have a valid file size and MD5 checksum.

**Scripts run**
>cd /share/dropbox/user221.102628
>sudo calculateChecksumSizes 102628
*Compare script run and OK
>cd
>sudo datasetUpload
*Done, no error --> log file: [java.log](https://github.com/user-attachments/files/18196193/java.log)
>cd /share/dropbox/user221.102628
>sudo postUpload --doi 102628 --dropbox user221.102628
*All OK

**Screenshots**
![Image](https://github.com/user-attachments/assets/c494f840-3f54-47ba-bef8-f76f6754e27a)

**Additional context**
-Related to dataset 102628 https://github.com/gigascience/dataset-tracking/issues/105
-Potentially same problem as dataset 102636 https://github.com/gigascience/dataset-tracking/issues/98

**Comment by kencho51** [comment]
Hi @molcretb,

When I go to the mock up page at here: https://gigadb.org/dataset/view/id/102628/token/xIoEq4amYH39BT6g/Files_page/5, I can see the file size and the md5 checksum values:
![Image](https://github.com/user-attachments/assets/f6e04da0-1f48-4426-9913-5cb2fed1e5af)

I think it is related to the browser caching issue.

**Comment by only1chunts** [comment]
@ken, the issue in the example was fixed manually as it needed to be released. 
Its a real bug, we're just not sure what exactly the trigger is, so diagnosis of the cause is difficult.

**Comment by kencho51** [comment]
Hi @pli888,

I have tried to ingest this dataset spreadsheet into my local gigadb, and I got this error:
```
GigaDBUpload_v19_102628_GIGA-D-24-00205.xls
**End error: GigaDBUpload_v19_102628_GIGA-D-24-00205.xls
org.postgresql.util.PSQLException: ERROR: insert or update on table "sample_attribute" violates foreign key constraint "sample_attribute_fkey"
  Detail: Key (attribute_id)=(0) is not present in table "attribute".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)
	at Database.execute(Database.java:456)
	at Main.processExcel2Database(Main.java:90)
	at Main.processExcel(Main.java:130)
	at Main.main(Main.java:168)
```

It seems the problem may stem from the spreadsheet itself.

**Comment by molcretb** [comment]
Encountered same issue with dataset 102669:
files 'Table_S1.csv', 'Table_S2.csv' & 'Table_S3.csv' had no MD5 attribute and filesize = 0 after spreadsheet ingested into GigaDB (but listed in the 'file' tab')
The data type was initially 'MS supplemental file' (changed later to 'tabular data')
I manually edited the attributes to add the MD5 and filesize.

The original spreadsheet: 

[GigaDBUpload_v19_102669_GIGA-D-24-00363.xls](https://github.com/user-attachments/files/18979446/GigaDBUpload_v19_102669_GIGA-D-24-00363.xls)

**Comment by only1chunts** [comment]
@tuli @molcretb @YFan0019 do we think this is a high impact bug? would the time being spent on trying to fix this be better spent on creating the tools to upload file information directly to the database through a CSV uploader on the admin pages (aka part of the file upload tool)?

**Comment by molcretb** [comment]
probably not a high impact bug, it appears that it has only affected a few files from a few datasets, fixing the missing values is quick and easy to do

**Comment by only1chunts** [comment]
agreed in it status meeting that this is a low priority and therefore no tech person will spend more time on this now, so closing the ticket now. 
We can reopen if it becomes more of a problem for curators.

**Comment by tuli** [comment]
I have come across the same problem when running 
sudo postUpload --doi 102710 --dropbox user331

It took many hours to run and only 2 of the 69 files have had file size and md5 populated. 

Both 102710.filesizes & 102710.md5 are in /share/dropbox/user331

This will take me a long time to do manually. 

![Image](https://github.com/user-attachments/assets/7d91275d-42da-4666-9b3d-9ea808e8c3c4)

**Comment by tuli** [comment]
@pli888 this is the spreadsheet I uploaded: 

[GigaDBUpload_v19_102710_GIGA-D-25-00052-final.xls](https://github.com/user-attachments/files/20282051/GigaDBUpload_v19_102710_GIGA-D-25-00052-final.xls)

**Comment by pli888** [comment]
@tuli When I opened `GigaDBUpload_v19_102710_GIGA-D-25-00052-final.xls`, the Study tab has 102719 as its DOI number. If this Excel file was uploaded then the listed files will have been associated with dataset 102719 in the database. The post upload tool would subsequently not be able update the dataset with metadata from 102710.md5 and 102710.filesizes. 

The user331 dropbox contains 531 gigabytes of data with gigabyte-size files. This will explain why md5 calculations would have taken hours to run.

I also noticed the author_list row in Study tab has a typo in the second author - `Belén Gómez-Pardo [0000-0003-3548-6306[;`. If I corrected this typo and updated Excel file to have 102710 as its DOI then I was able to update file sizes and md5 values in database.

**Comment by pli888** [comment]
Closing this ticket because cause of upload problem was identified for `GigaDBUpload_v19_102710_GIGA-D-25-00052-final.xls`.

**Comment by molcretb** [comment]
Missing MD5 values after running the postUpload script for the three BUSCO files, dataset 102722
See https://github.com/gigascience/dataset-tracking/issues/190
Spreadsheet used: 

[GigaDBUpload_v18_102722_DRR-202404-04_v2.xls](https://github.com/user-attachments/files/20518969/GigaDBUpload_v18_102722_DRR-202404-04_v2.xls)

**Comment by pli888** [comment]
It looks like the file metadata console tool has been updating the md5 value of another file with the same filename from another dataset. For example, dataset 102722 contains a file called `BUSCO_full_table.tsv` which is also found in other datasets such as 102573, 102356, 102233.


There will be an opportunity to correct files that have been updated with wrong md5 values in ticket #373.

**Comment by pli888** [comment]
Closing this ticket because there is PR #2345 to fix this problem.
